services:
  nextjs:
    build:
      context: .
      dockerfile: ./compose/production/next/Dockerfile
    image: production_consultapixccs
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - usernameBC=${usernameBC}
      - passwordBC=${passwordBC}
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./compose/production/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: consultapixccs_production_postgres
    volumes:
      - consultapixccs_postgres_data:/var/lib/postgresql/data
      - consultapixccs_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  consultapixccs_postgres_data: {}
  consultapixccs_postgres_data_backups: {}
